### ISSUE TITLE
Task Distribution's

### ISSUE THREAD

**Issue by hcngo** [tmlai/CMPUT410-TTHE-Group-Project#4]
Database Layer:  
@tmlai looks into the completed Database Layer which implements the database interface to see the list of suggested methods. START IMPLEMENTING from BOTTOM UP
@tmlai check out PDO mysql to see how to use PDO. @hcngo has implemented the addProduct() to facilitate adding common products.

Front end:  
@cedwin will be assisting @tullyj to implement the front end. PLEASE document all PHP scripts you need as well as the expected return value + format into the "report.md".

**Comment by tmlai** [comment]
@hcngo  what do you mean by completed Database Layer?

**Comment by tmlai** [comment]
Done
