### ISSUE TITLE
April 3 - Meeting

### ISSUE THREAD

**Issue by tullyj** [tmlai/CMPUT410-TTHE-Group-Project#5]
FRONT_END
    + add thumbnails to category/search pages
    + outstanding orders 
        +   add beside view cart a profile button which is where to see 
            outstanding orders
    + Profile (displays username once signed in)
        + change user info
        + outstanding orders
        + admin options (if applicable)
    Admin 
        + Calculate statistics based on
            + Customer dropdown
            + Products
            + Stores
            + time period/range
            + Top 'n' selling products (ie: top 5)
                + Can select individual statistics to be displayed as a list for 
                  each for Customers, Products, and Stores
LIST FORMATTING
    if cust/store/product is ind. but others are not, copy values to other list
    elements

MIDDLE_END
    + add htaccess
![20130403_161139](https://f.cloud.github.com/assets/2432857/336577/efcf5d70-9cab-11e2-94a7-684892e9e3f9.jpg)
![20130403_161108](https://f.cloud.github.com/assets/2432857/336578/f74584f8-9cab-11e2-93f3-1ab10907f9d6.jpg)

**Comment by tmlai** [comment]
done. This should be a wiki document.
